PierresTreats/Models/Treat.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
    public class Treat
    {
        public Treat()
        {
            this.Flavors = new HashSet<FlavorTreat>();
        }

        public int TreatId { get; set; }
        public string Description { get; set; }
        public virtual ApplicationUser User { get; set; } //new line

        public ICollection<FlavorTreat> Flavors { get;}
    }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userTreats = _db.Treats.Where(entry => entry.User.Id == currentUser.Id);
        return View(userTreats);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        if (FlavorId != 0)
        {
            _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.Flavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
        var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
        return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
        if (FlavorId != 0)
        {
            _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        }
        _db.Entry(treat).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
        var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
        return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
        if (FlavorId != 0)
        {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        _db.Treats.Remove(thisTreat);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
        var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreat.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@model PierresTreats.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor for this treat: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresTreats/Views/Treats/Create.cshtml
@model PierresTreats.Models.Treat

<h4>Add a new treat</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Add new treat" class="btn btn-success" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>

PierresTreats/Views/Treats/Delete.cshtml
@model PierresTreats.Models.Treat

<h2>Are you sure you want to delete this treat?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierresTreats/Views/Treats/Details.cshtml
@model PierresTreats.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>


@if(@Model.Flavors.Count == 0)
{
  <p>This treat does not have any flavors</p>
}
else
{
  <h4>Flavors in this treat:</h4>
  <ul>
  @foreach(var join in Model.Flavors)
  {
    <li>@join.Flavor.Name</li>
    @using (Html.BeginForm("DeleteFlavor", "Treats"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>

PierresTreats/Views/Treats/Edit.cshtml
@model PierresTreats.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)<br>

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")<br>

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresTreats/Views/Treats/Index.cshtml
@using PierresTreats.Models;
@model IEnumerable<PierresTreats.Models.Treat>

<h1>Treats for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Description}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
} 
else
{
  <h3>No treats have been added yet!</h3>
}

<p>@Html.ActionLink("Add new treat", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>